apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-devsecops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-devsecops-demo
  template:
    metadata:
      labels:
        app: java-devsecops-demo
    spec:
      containers:
      - name: app
        image: localhost:5000/java-devsecops-demo:dev
        ports:
        - containerPort: 8080